name: Continue On Error Example

on: push

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: This step fails
        run: exit 1
        continue-on-error: false

      - name: Workflow continues
        run: echo "Next step still runs"