name: Mixed Example

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building"

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Linting"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Testing"

  deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - run: echo "Deploying"