name: Real-world example

on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - run: npm run build

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: docker build -t app .

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - run: echo "Deploying to Cloud Run"